### ISSUE TITLE
bucket for pre-trained model not available

### ISSUE THREAD

**Issue by guermonprez** [lukerm/find-tune#1]
hello

it looks like the bucket s3://lukerm-ds-open/find-tune/data/
with pre-trained model is not available anymore.
Would be nice to have it, or have the files in the data folder on github

thanks

**Comment by lukerm** [comment]
Hi Paul,

I have re-opened this bucket now, so you should be able to access it. Let me know if you can access it and how you get on after that. 

Thanks for your interest,
Luke
